apiVersion: v1
kind: Service
metadata:
  labels:
    app: ocr-service-canary
  name: ocr-service-canary
spec:
  ports:
  - name: 80-80
    port: 9099
    protocol: TCP
    targetPort: 9099
  selector:
    load-balancer-ocr-service-canary: "true"
  sessionAffinity: None
  type: LoadBalancer
